import requests
import pandas as pd
from bs4 import BeautifulSoup


colleges = {
    "Air Force Falcons": "air-force",
    "Akron Zips": "akron",
    "Alabama A&M Bulldogs": "aamu",
    "Alabama Crimson Tide": "alabama",
    "Alabama State Hornets": "alabama-state",
    "Albany Great Danes": "albany",
    "Alcorn State Braves": "alcorn-state",
    "Appalachian State Mountaineers": "appalachian-state",
    "Arizona State Sun Devils": "arizona-state",
    "Arizona Wildcats": "arizona",
    "Arkansas Razorbacks": "arkansas",
    "Arkansas State Red Wolves": "arkansas-state",
    "Arkansas-Pine Bluff Golden Lions": "arkansas-pine-bluff",
    "Army Black Knights": "army",
    "Auburn Tigers": "auburn",
    "Ball State Cardinals": "ball-state",
    "Baylor Bears": "baylor",
    "Bethune-Cookman Wildcats": "bethune-cookman",
    "Boise State Broncos": "boise-state",
    "Boston College Eagles": "boston-college",
    "Bowling Green Falcons": "bowling-green",
    "Brigham Young Cougars": "byu",
    "Brown Bears": "brown",
    "Bryant Bulldogs": "bryant",
    "Bucknell Bison": "bucknell",
    "Buffalo Bulls": "buffalo",
    "Butler Bulldogs": "butler",
    "Cal Poly Mustangs": "cal-poly",
    "Cal State Bakersfield Roadrunners": "cal-state-bakersfield",
    "California Golden Bears": "california",
    "Campbell Fighting Camels": "campbell",
    "Central Arkansas Bears": "central-arkansas",
    "Central Connecticut State Blue Devils": "ccsu",
    "Central Michigan Chippewas": "central-michigan",
    "Charleston Southern Buccaneers": "charleston-southern",
    "Charlotte 49ers": "charlotte",
    "Chattanooga Mocs": "chattanooga",
    "Cincinnati Bearcats": "cincinnati",
    "Clemson Tigers": "clemson",
    "Coastal Carolina Chanticleers": "coastal-carolina",
    "Colgate Raiders": "colgate",
    "Colorado Buffaloes": "colorado",
    "Colorado State Rams": "colorado-state",
    "Columbia Lions": "columbia",
    "Connecticut Huskies": "uconn",
    "Cornell Big Red": "cornell",
    "Dartmouth Big Green": "dartmouth",
    "Davidson Wildcats": "davidson",
    "Dayton Flyers": "dayton",
    "Delaware Fightin' Blue Hens": "delaware",
    "Delaware State Hornets": "delaware-state",
    "Drake Bulldogs": "drake",
    "Duke Blue Devils": "duke",
    "Duquesne Dukes": "duquesne",
    "East Carolina Pirates": "east-carolina",
    "East Tennessee State Buccaneers": "etsu",
    "Eastern Illinois Panthers": "eastern-illinois",
    "Eastern Kentucky Colonels": "eastern-kentucky",
    "Eastern Michigan Eagles": "eastern-michigan",
    "Eastern Washington Eagles": "eastern-washington",
    "Elon Phoenix": "elon",
    "FIU Golden Panthers": "florida-international",
    "Florida A&M Rattlers": "famu",
    "Florida Atlantic Owls": "florida-atlantic",
    "Florida Gators": "florida",
    "Florida State Seminoles": "florida-state",
    "Fordham Rams": "fordham",
    "Fresno State Bulldogs": "fresno-state",
    "Furman Paladins": "furman",
    "Gardner-Webb Runnin' Bulldogs": "gardner-webb",
    "Georgetown Hoyas": "georgetown",
    "Georgia Bulldogs": "georgia",
    "Georgia Southern Eagles": "georgia-southern",
    "Georgia State Panthers": "georgia-state",
    "Georgia Tech Yellow Jackets": "georgia-tech",
    "Grambling State Tigers": "grambling-state",
    "Hampton Pirates": "hampton",
    "Harvard Crimson": "harvard",
    "Hawaii Rainbow Warriors": "hawaii",
    "Holy Cross Crusaders": "holy-cross",
    "Houston Christian Huskies": "houston-christian",
    "Houston Cougars": "houston",
    "Howard Bison": "howard",
    "Idaho State Bengals": "idaho-state",
    "Idaho Vandals": "idaho",
    "Illinois Fighting Illini": "illinois",
    "Illinois State Redbirds": "illinois-state",
    "Incarnate Word Cardinals": "uiw",
    "Indiana Hoosiers": "indiana",
    "Indiana State Sycamores": "indiana-state",
    "Iowa Hawkeyes": "iowa",
    "Iowa State Cyclones": "iowa-state",
    "Jackson State Tigers": "jackson-state",
    "Jacksonville Dolphins": "jacksonville",
    "Jacksonville State Gamecocks": "jacksonville-state",
    "James Madison Dukes": "james-madison",
    "Kansas Jayhawks": "kansas",
    "Kansas State Wildcats": "kansas-state",
    "Kennesaw State Owls": "kennesaw-state",
    "Kent State Golden Flashes": "kent-state",
    "Kentucky Wildcats": "kentucky",
    "LIU Sharks": "liu-brooklyn",
    "LSU Tigers": "lsu",
    "Lafayette Leopards": "lafayette",
    "Lamar Cardinals": "lamar",
    "Lehigh Mountain Hawks": "lehigh",
    "Liberty Flames": "liberty",
    "Louisiana Ragin' Cajuns": "louisiana",
    "Louisiana Tech Bulldogs": "louisiana-tech",
    "Louisiana-Monroe Warhawks": "louisiana-monroe",
    "Louisville Cardinals": "louisville",
    "Maine Black Bears": "maine",
    "Marist Red Foxes": "marist",
    "Marshall Thundering Herd": "marshall",
    "Maryland Terrapins": "maryland",
    "McNeese State Cowboys": "mcneese-state",
    "Memphis Tigers": "memphis",
    "Mercer Bears": "mercer",
    "Merrimack College": "247sports.com",
    "Miami (OH) RedHawks": "miami-ohio",
    "Miami Hurricanes": "miami",
    "Michigan State Spartans": "michigan-state",
    "Michigan Wolverines": "michigan",
    "Middle Tennessee State Blue Raiders": "middle-tennessee-state",
    "Minnesota Golden Gophers": "minnesota",
    "Mississippi State Bulldogs": "mississippi-state",
    "Mississippi Valley State Delta Devils": "mvsu",
    "Missouri State Bears": "missouri-state",
    "Missouri Tigers": "missouri",
    "Monmouth Hawks": "monmouth",
    "Montana Grizzlies": "montana",
    "Montana State Bobcats": "montana-state",
    "Morehead State Eagles": "morehead-state",
    "Morgan State Golden Bears": "morgan-state",
    "Murray State Racers": "murray-state",
    "NC State Wolfpack": "north-carolina-state",
    "Navy Midshipmen": "navy",
    "Nebraska Cornhuskers": "nebraska",
    "Nevada Wolf Pack": "nevada",
    "New Hampshire Wildcats": "new-hampshire",
    "New Mexico Lobos": "new-mexico",
    "New Mexico State Aggies": "new-mexico-state",
    "Nicholls State Colonels": "nicholls-state",
    "Norfolk State Spartans": "norfolk-state",
    "North Carolina A&T Aggies": "ncat",
    "North Carolina Central Eagles": "nccu",
    "North Carolina Tar Heels": "north-carolina",
    "North Dakota Fighting Hawks": "north-dakota",
    "North Dakota State Bison": "north-dakota-state",
    "North Texas Mean Green": "north-texas",
    "Northern Arizona Lumberjacks": "northern-arizona",
    "Northern Colorado Bears": "northern-colorado",
    "Northern Illinois Huskies": "northern-illinois",
    "Northern Iowa Panthers": "northern-iowa",
    "Northwestern State Demons": "northwestern-state",
    "Northwestern Wildcats": "northwestern",
    "Notre Dame Fighting Irish": "notre-dame",
    "Ohio Bobcats": "ohio",
    "Ohio State Buckeyes": "ohio-state",
    "Oklahoma Sooners": "oklahoma",
    "Oklahoma State Cowboys": "oklahoma-state",
    "Old Dominion Monarchs": "old-dominion",
    "Ole Miss Rebels": "ole-miss",
    "Oregon Ducks": "oregon",
    "Oregon State Beavers": "oregon-state",
    "Penn State Nittany Lions": "penn-state",
    "Pennsylvania Quakers": "pennsylvania",
    "Pittsburgh Panthers": "pittsburgh",
    "Portland State Vikings": "portland-state",
    "Prairie View A&M Panthers": "pvamu",
    "Presbyterian Blue Hose": "presbyterian",
    "Princeton Tigers": "princeton",
    "Purdue Boilermakers": "purdue",
    "Rhode Island Rams": "rhode-island",
    "Rice Owls": "rice",
    "Richmond Spiders": "richmond",
    "Robert Morris Colonials": "robert-morris",
    "Rutgers Scarlet Knights": "rutgers",
    "SMU Mustangs": "smu",
    "Sacramento State Hornets": "sacramento-state",
    "Sacred Heart Pioneers": "sacred-heart",
    "Saint Francis (PA) Red Flash": "saint-francis",
    "Sam Houston State Bearkats": "sam-houston-state",
    "Samford Bulldogs": "samford",
    "San Diego State Aztecs": "san-diego-state",
    "San Diego Toreros": "san-diego",
    "San Jose State Spartans": "san-jose-state",
    "South Alabama Jaguars": "south-alabama",
    "South Carolina Gamecocks": "south-carolina",
    "South Carolina State Bulldogs": "south-carolina-state",
    "South Dakota Coyotes": "south-dakota",
    "South Dakota State Jackrabbits": "south-dakota-state",
    "South Florida Bulls": "south-florida",
    "Southeast Missouri State Redhawks": "semo",
    "Southeastern Louisiana Lions": "southeastern-louisiana",
    "Southern Illinois Salukis": "southern-illinois",
    "Southern Jaguars": "southern",
    "Southern Miss Golden Eagles": "southern-mississippi",
    "Stanford Cardinal": "stanford",
    "Stephen F. Austin Lumberjacks": "sfasu",
    "Stetson Hatters": "stetson",
    "Stonehill Skyhawks": "247sports.com",
    "Stony Brook Seawolves": "stony-brook",
    "Syracuse Orange": "syracuse",
    "TCU Horned Frogs": "tcu",
    "Temple Owls": "temple",
    "Tennessee State Tigers": "tennessee-state",
    "Tennessee Tech Golden Eagles": "tennessee-tech",
    "Tennessee Volunteers": "tennessee",
    "Texas A&M Aggies": "texas-am",
    "Texas Longhorns": "texas",
    "Texas Southern Tigers": "texas-southern",
    "Texas State Bobcats": "texas-state",
    "Texas Tech Red Raiders": "texas-tech",
    "The Citadel Bulldogs": "citadel",
    "Toledo Rockets": "toledo",
    "Towson Tigers": "towson",
    "Troy Trojans": "troy",
    "Tulane Green Wave": "tulane",
    "Tulsa Golden Hurricane": "tulsa",
    "UAB Blazers": "alabama-birmingham",
    "UC Davis Aggies": "uc-davis",
    "UCF Knights": "central-florida",
    "UCLA Bruins": "ucla",
    "UMass Minutemen": "massachusetts",
    "UNLV Rebels": "unlv",
    "USC Trojans": "usc",
    "UT Martin Skyhawks": "tennessee-martin",
    "UTEP Miners": "utep",
    "UTSA Roadrunners": "utsa",
    "Utah State Aggies": "utah-state",
    "Utah Utes": "utah",
    "Valparaiso Beacons": "valparaiso",
    "Vanderbilt Commodores": "vanderbilt",
    "Villanova Wildcats": "villanova",
    "Virginia Cavaliers": "virginia",
    "Virginia Military Institute Keydets": "vmi",
    "Virginia Tech Hokies": "virginia-tech",
    "Wagner Seahawks": "wagner",
    "Wake Forest Demon Deacons": "wake-forest",
    "Washington Huskies": "washington",
    "Washington State Cougars": "washington-state",
    "Weber State Wildcats": "weber-state",
    "West Virginia Mountaineers": "west-virginia",
    "Western Carolina Catamounts": "western-carolina",
    "Western Illinois Leathernecks": "western-illinois",
    "Western Kentucky Hilltoppers": "western-kentucky",
    "Western Michigan Broncos": "western-michigan",
    "William & Mary Tribe": "wm",
    "Wisconsin Badgers": "wisconsin",
    "Wofford Terriers": "wofford",
    "Wyoming Cowboys": "wyoming",
    "Yale Bulldogs": "yale",
    "Youngstown State Penguins": "youngstown-state",
}

recruit_data = pd.DataFrame(columns=["Year", "Name", "Position", "College", "Rating"])
count = 0

headers = {"User-Agent": "..."}

for college in colleges:
    for year in range(2004, 2024):
        url = requests.get(
            f"https://247sports.com/college/{colleges[college]}/Season/{year}-Football/Commits/?rankings=composite",
            headers=headers,
        )

        soup = BeautifulSoup(url.text, "html.parser")

        try:
            table = soup.find("ul", attrs={"class": "ri-page__list"}).find_all("li")
        except:
            continue

        for tablepart in table[1:]:
            try:
                columns = tablepart.find("div").find_all("div")

                recruit = {
                    "Year": year,
                    "Name": columns[1].find("a").text,
                    "Position": columns[-1].text.strip(),
                    "College": college,
                    "Rating": columns[4].find_all("span")[5].text,
                }

                print(recruit)

                recruit_data.loc[len(recruit_data)] = recruit

            except:
                break

print(recruit_data)
recruit_data.to_csv("data/recruit_data.csv", index=False)
