import requests
import pandas as pd
from bs4 import BeautifulSoup


ids = {
    "Abilene Christian Wildcats": "2000",
    "Air Force Falcons": "2005",
    "Akron Zips": "2006",
    "Alabama Crimson Tide": "333",
    "Alabama A&M Bulldogs": "2010",
    "Alabama State Hornets": "2011",
    "Alcorn State Braves": "2016",
    "Appalachian State Mountaineers": "2026",
    "Arizona Wildcats": "12",
    "Arizona State Sun Devils": "9",
    "Arkansas Razorbacks": "8",
    "Arkansas State Red Wolves": "2032",
    "Arkansas-Pine Bluff Golden Lions": "2029",
    "Army Black Knights": "349",
    "Auburn Tigers": "2",
    "Austin Peay Governors": "2046",
    "BYU Cougars": "252",
    "Ball State Cardinals": "2050",
    "Baylor Bears": "239",
    "Bethune-Cookman Wildcats": "2065",
    "Boise State Broncos": "68",
    "Boston College Eagles": "103",
    "Bowling Green Falcons": "189",
    "Brown Bears": "225",
    "Bryant Bulldogs": "2803",
    "Bucknell Bison": "2083",
    "Buffalo Bulls": "2084",
    "Butler Bulldogs": "2086",
    "Cal Poly Mustangs": "13",
    "California Golden Bears": "25",
    "Campbell Fighting Camels": "2097",
    "Central Arkansas Bears": "2110",
    "Central Connecticut Blue Devils": "2115",
    "Central Michigan Chippewas": "2117",
    "Charleston Southern Buccaneers": "2127",
    "Charlotte 49ers": "2429",
    "Chattanooga Mocs": "236",
    "Cincinnati Bearcats": "2132",
    "Clemson Tigers": "228",
    "Coastal Carolina Chanticleers": "324",
    "Colgate Raiders": "2142",
    "Colorado Buffaloes": "38",
    "Colorado State Rams": "36",
    "Columbia Lions": "171",
    "Cornell Big Red": "172",
    "Dartmouth Big Green": "159",
    "Davidson Wildcats": "2166",
    "Dayton Flyers": "2168",
    "Delaware Fightin' Blue Hens": "48",
    "Delaware State Hornets": "2169",
    "Drake Bulldogs": "2181",
    "Duke Blue Devils": "150",
    "Duquesne Dukes": "2184",
    "East Carolina Pirates": "151",
    "East Tennessee State Buccaneers": "2193",
    "Eastern Illinois Panthers": "2197",
    "Eastern Kentucky Colonels": "2198",
    "Eastern Michigan Eagles": "2199",
    "Eastern Washington Eagles": "331",
    "Elon Phoenix": "2210",
    "Florida Gators": "57",
    "Florida A&M Rattlers": "50",
    "Florida Atlantic Owls": "2226",
    "Florida International Panthers": "2229",
    "Florida State Seminoles": "52",
    "Fordham Rams": "2230",
    "Fresno State Bulldogs": "278",
    "Furman Paladins": "231",
    "Gardner-Webb Runnin' Bulldogs": "2241",
    "Georgetown Hoyas": "46",
    "Georgia Bulldogs": "61",
    "Georgia Southern Eagles": "290",
    "Georgia State Panthers": "2247",
    "Georgia Tech Yellow Jackets": "59",
    "Grambling Tigers": "2755",
    "Hampton Pirates": "2261",
    "Harvard Crimson": "108",
    "Hawai'i Rainbow Warriors": "62",
    "Holy Cross Crusaders": "107",
    "Houston Cougars": "248",
    "Houston Christian Huskies": "2277",
    "Howard Bison": "47",
    "Idaho Vandals": "70",
    "Idaho State Bengals": "304",
    "Illinois Fighting Illini": "356",
    "Illinois State Redbirds": "2287",
    "Incarnate Word Cardinals": "2916",
    "Indiana Hoosiers": "84",
    "Indiana State Sycamores": "282",
    "Iowa Hawkeyes": "2294",
    "Iowa State Cyclones": "66",
    "Jackson State Tigers": "2296",
    "Jacksonville State Gamecocks": "55",
    "James Madison Dukes": "256",
    "Kansas Jayhawks": "2305",
    "Kansas State Wildcats": "2306",
    "Kennesaw State Owls": "338",
    "Kent State Golden Flashes": "2309",
    "Kentucky Wildcats": "96",
    "LSU Tigers": "99",
    "Lafayette Leopards": "322",
    "Lamar Cardinals": "2320",
    "Lehigh Mountain Hawks": "2329",
    "Liberty Flames": "2335",
    "Lindenwood Lions": "2815",
    "Long Island University Sharks": "2341",
    "Louisiana Ragin' Cajuns": "309",
    "Louisiana Tech Bulldogs": "2348",
    "Louisville Cardinals": "97",
    "Maine Black Bears": "311",
    "Marist Red Foxes": "2368",
    "Marshall Thundering Herd": "276",
    "Maryland Terrapins": "120",
    "Massachusetts Minutemen": "113",
    "McNeese Cowboys": "2377",
    "Memphis Tigers": "235",
    "Mercer Bears": "2382",
    "Merrimack Warriors": "2771",
    "Miami Hurricanes": "2390",
    "Miami (OH) RedHawks": "193",
    "Michigan Wolverines": "130",
    "Michigan State Spartans": "127",
    "Middle Tennessee Blue Raiders": "2393",
    "Minnesota Golden Gophers": "135",
    "Mississippi State Bulldogs": "344",
    "Mississippi Valley State Delta Devils": "2400",
    "Missouri Tigers": "142",
    "Missouri State Bears": "2623",
    "Monmouth Hawks": "2405",
    "Montana Grizzlies": "149",
    "Montana State Bobcats": "147",
    "Morehead State Eagles": "2413",
    "Morgan State Bears": "2415",
    "Murray State Racers": "93",
    "NC State Wolfpack": "152",
    "Navy Midshipmen": "2426",
    "Nebraska Cornhuskers": "158",
    "Nevada Wolf Pack": "2440",
    "New Hampshire Wildcats": "160",
    "New Mexico Lobos": "167",
    "New Mexico State Aggies": "166",
    "Nicholls Colonels": "2447",
    "Norfolk State Spartans": "2450",
    "North Alabama Lions": "2453",
    "North Carolina Tar Heels": "153",
    "North Carolina A&T Aggies": "2448",
    "North Carolina Central Eagles": "2428",
    "North Dakota Fighting Hawks": "155",
    "North Dakota State Bison": "2449",
    "North Texas Mean Green": "249",
    "Northern Arizona Lumberjacks": "2464",
    "Northern Colorado Bears": "2458",
    "Northern Illinois Huskies": "2459",
    "Northern Iowa Panthers": "2460",
    "Northwestern Wildcats": "77",
    "Northwestern State Demons": "2466",
    "Notre Dame Fighting Irish": "87",
    "Ohio Bobcats": "195",
    "Ohio State Buckeyes": "194",
    "Oklahoma Sooners": "201",
    "Oklahoma State Cowboys": "197",
    "Old Dominion Monarchs": "295",
    "Ole Miss Rebels": "145",
    "Oregon Ducks": "2483",
    "Oregon State Beavers": "204",
    "Penn State Nittany Lions": "213",
    "Pennsylvania Quakers": "219",
    "Pittsburgh Panthers": "221",
    "Portland State Vikings": "2502",
    "Prairie View A&M Panthers": "2504",
    "Presbyterian Blue Hose": "2506",
    "Princeton Tigers": "163",
    "Purdue Boilermakers": "2509",
    "Rhode Island Rams": "227",
    "Rice Owls": "242",
    "Richmond Spiders": "257",
    "Robert Morris Colonials": "2523",
    "Rutgers Scarlet Knights": "164",
    "SE Louisiana Lions": "2545",
    "SMU Mustangs": "2567",
    "Sacramento State Hornets": "16",
    "Sacred Heart Pioneers": "2529",
    "Sam Houston Bearkats": "2534",
    "Samford Bulldogs": "2535",
    "San Diego Toreros": "301",
    "San Diego State Aztecs": "21",
    "San José State Spartans": "23",
    "South Alabama Jaguars": "6",
    "South Carolina Gamecocks": "2579",
    "South Carolina State Bulldogs": "2569",
    "South Dakota Coyotes": "233",
    "South Dakota State Jackrabbits": "2571",
    "South Florida Bulls": "58",
    "Southeast Missouri State Redhawks": "2546",
    "Southern Jaguars": "2582",
    "Southern Illinois Salukis": "79",
    "Southern Miss Golden Eagles": "2572",
    "Southern Utah Thunderbirds": "253",
    "St. Francis (PA) Red Flash": "2598",
    "St. Thomas-Minnesota Tommies": "2900",
    "Stanford Cardinal": "24",
    "Stephen F. Austin Lumberjacks": "2617",
    "Stetson Hatters": "56",
    "Stonehill Skyhawks": "284",
    "Stony Brook Seawolves": "2619",
    "Syracuse Orange": "183",
    "TCU Horned Frogs": "2628",
    "Tarleton State Texans": "2627",
    "Temple Owls": "218",
    "Tennessee Volunteers": "2633",
    "Tennessee State Tigers": "2634",
    "Tennessee Tech Golden Eagles": "2635",
    "Texas Longhorns": "251",
    "Texas A&M Aggies": "245",
    "Texas A&M-Commerce Lions": "2837",
    "Texas Southern Tigers": "2640",
    "Texas State Bobcats": "326",
    "Texas Tech Red Raiders": "2641",
    "The Citadel Bulldogs": "2643",
    "Toledo Rockets": "2649",
    "Towson Tigers": "119",
    "Troy Trojans": "2653",
    "Tulane Green Wave": "2655",
    "Tulsa Golden Hurricane": "202",
    "UAB Blazers": "5",
    "UAlbany Great Danes": "399",
    "UC Davis Aggies": "302",
    "UCF Knights": "2116",
    "UCLA Bruins": "26",
    "UConn Huskies": "41",
    "UL Monroe Warhawks": "2433",
    "UNLV Rebels": "2439",
    "USC Trojans": "30",
    "UT Martin Skyhawks": "2630",
    "UTEP Miners": "2638",
    "UTSA Roadrunners": "2636",
    "Utah Utes": "254",
    "Utah State Aggies": "328",
    "Utah Tech Trailblazers": "3101",
    "VMI Keydets": "2678",
    "Valparaiso Beacons": "2674",
    "Vanderbilt Commodores": "238",
    "Villanova Wildcats": "222",
    "Virginia Cavaliers": "258",
    "Virginia Tech Hokies": "259",
    "Wagner Seahawks": "2681",
    "Wake Forest Demon Deacons": "154",
    "Washington Huskies": "264",
    "Washington State Cougars": "265",
    "Weber State Wildcats": "2692",
    "West Virginia Mountaineers": "277",
    "Western Carolina Catamounts": "2717",
    "Western Illinois Leathernecks": "2710",
    "Western Kentucky Hilltoppers": "98",
    "Western Michigan Broncos": "2711",
    "William & Mary Tribe": "2729",
    "Wisconsin Badgers": "275",
    "Wofford Terriers": "2747",
    "Wyoming Cowboys": "2751",
    "Yale Bulldogs": "43",
    "Youngstown State Penguins": "2754",
}

cats = [
    "Total Points Per Game",
    "Total Points",
    "Total Touchdowns",
    "1st Downs",
    "Total 1st downs",
    "Rushing 1st downs",
    "Passing 1st downs",
    "1st downs by penalty",
    "3rd down efficiency",
    "3rd down %",
    "4th down efficiency",
    "4th down %",
    "Passing",
    "Comp-Att",
    "Net Passing Yards",
    "Yards Per Pass Attempt",
    "Net Passing Yards Per Game",
    "Passing Touchdowns",
    "Interceptions",
    "Sacks-Yards Lost",
    "Rushing",
    "Rushing Attempts",
    "Rushing Yards",
    "Yards Per Rush Attempt",
    "Rushing Yards Per Game",
    "Rushing Touchdowns",
    "Offense",
    "Total Offensive Plays",
    "Total Yards",
    "Yards Per Game",
    "Returns",
    "Kickoffs: Total",
    "Average Kickoff Return Yards",
    "Punt: Total",
    "Average Punt Return Yards",
    "INT: Total",
    "Average Interception Yards",
    "Kicking",
    "Net Average Punt Yards",
    "Punt: Total Yards",
    "FG: Good-Attempts",
    "Touchback Percentage",
    "Penalties",
    "Total-Yards",
    "Avg. Per Game (YDS)",
    "Time of Possession",
    "Possession Time Seconds",
    "Miscellaneous",
    "Fumbles-Lost",
    "Turnover Ratio",
]

headers = {"User-Agent": "..."}

college_data = pd.DataFrame(columns=["Year", "College Name"] + cats)

for team_name in ids:
    for year in range(2004, 2024):
        url = requests.get(
            f"https://www.espn.com/college-football/team/stats/_/type/team/id/{ids[team_name]}/season/{year}",
            headers=headers,
        )
        soup = BeautifulSoup(url.text, "html.parser")

        try:
            rows = soup.find("tbody", attrs={"class": "Table__TBODY"}).find_all("tr")
        except:
            continue

        program = {
            "Year": year,
            "College Name": team_name,
        }

        rows = soup.find_all("tbody", attrs={"class": "Table__TBODY"})[1].find_all("tr")

        count = 0
        for row in rows:
            if not row.text == "":
                program[cats[count]] = row.text
            else:
                program[cats[count]] = None
            count += 1

        print(program)
        print()

        college_data.loc[len(college_data)] = program

print(college_data)
college_data.to_csv("data/college_data.csv", index=False)
